In [20]:
import numpy as np

In [38]:
np.arange(9).reshape()
np.reshape()

ValueError: cannot reshape array of size 9 into shape (2,2)

In [36]:
a = np.random.randn(3, 3)
b = np.array([1, 2, 3])
for i in np.nditer((a, b)):
    print(i)

(array(0.07716183), array(1))
(array(0.67636927), array(2))
(array(0.08379681), array(3))
(array(-1.56196435), array(1))
(array(-0.2447), array(2))
(array(-0.8750585), array(3))
(array(-2.63478061), array(1))
(array(0.72905805), array(2))
(array(-0.5714692), array(3))


In [34]:
for i in np.nditer(np.broadcast_to(np.array([1, 2, 3]), shape=(3, 3))):
    print(i)

1
2
3
1
2
3
1
2
3


In [10]:
a = np.array([1.123, 2.12313, 3.122], dtype=np.float32)
b = np.array([10, 20, 30], dtype=np.int32)
c = np.array([True, False, True])

In [9]:
b + a

array([11.12300003, 22.12313008, 33.12199998])

In [16]:
c + a

array([2.1230001, 2.12313  , 4.1219997], dtype=float32)

In [49]:
np.empty((3, 3)).dtype

dtype('float64')

In [47]:
a = np.arange(6).reshape(2, 1, 3)
print("oriShape:", a.shape)
print("oriStrides:", np.array(a.strides) / a.itemsize)
broadcastedA = np.broadcast_to(a, (2, 3, 4))
print("broadcastedShape:", broadcastedA.shape)
print("broadcastedStrides:", np.array(broadcastedA.strides) / broadcastedA.itemsize)

oriShape: (2, 1, 3)
oriStrides: [3. 3. 1.]


ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,1,3)  and requested shape (2,3,4)

(1, 3)

In [32]:
a = np.arange(6).reshape(1, 6)
print("oriShape:", a.shape)
print("oriStrides:", np.array(a.strides) / a.itemsize)
broadcastedA = np.broadcast_to(a, (2, 6))
print("broadcastedShape:", broadcastedA.shape)
print("broadcastedStrides:", np.array(broadcastedA.strides) / broadcastedA.itemsize)

oriShape: (1, 6)
oriStrides: [6. 1.]
broadcastedShape: (2, 6)
broadcastedStrides: [0. 1.]


In [33]:
a = np.arange(6).reshape(6)
print("oriShape:", a.shape)
print("oriStrides:", np.array(a.strides) / a.itemsize)
broadcastedA = np.broadcast_to(a, (2, 6))
print("broadcastedShape:", broadcastedA.shape)
print("broadcastedStrides:", np.array(broadcastedA.strides) / broadcastedA.itemsize)

oriShape: (6,)
oriStrides: [1.]
broadcastedShape: (2, 6)
broadcastedStrides: [0. 1.]


In [39]:
a = np.arange(6).reshape(6)
print("oriShape:", a.shape)
print("oriStrides:", np.array(a.strides) / a.itemsize)
broadcastedA = np.broadcast_to(a, (1, 1, 6))
print("broadcastedShape:", broadcastedA.shape)
print("broadcastedStrides:", np.array(broadcastedA.strides) / broadcastedA.itemsize)

oriShape: (6,)
oriStrides: [1.]
broadcastedShape: (1, 1, 6)
broadcastedStrides: [0. 0. 1.]


In [38]:
a = np.arange(6).reshape(6)
print("oriShape:", a.shape)
print("oriStrides:", np.array(a.strides) / a.itemsize)
broadcastedA = np.broadcast_to(a, (2, 1, 6))
print("broadcastedShape:", broadcastedA.shape)
print("broadcastedStrides:", np.array(broadcastedA.strides) / broadcastedA.itemsize)

oriShape: (6,)
oriStrides: [1.]
broadcastedShape: (2, 1, 6)
broadcastedStrides: [0. 0. 1.]


In [40]:
a = np.arange(6).reshape(1, 1, 6)
print("oriShape:", a.shape)
print("oriStrides:", np.array(a.strides) / a.itemsize)
broadcastedA = np.broadcast_to(a, (2, 1, 6))
print("broadcastedShape:", broadcastedA.shape)
print("broadcastedStrides:", np.array(broadcastedA.strides) / broadcastedA.itemsize)

oriShape: (1, 1, 6)
oriStrides: [6. 6. 1.]
broadcastedShape: (2, 1, 6)
broadcastedStrides: [0. 0. 1.]


In [44]:
a = np.arange(12).reshape(2, 6)
print("oriShape:", a.shape)
print("oriStrides:", np.array(a.strides) / a.itemsize)
broadcastedA = np.broadcast_to(a, (1, 2, 2, 6))
print("broadcastedShape:", broadcastedA.shape)
print("broadcastedStrides:", np.array(broadcastedA.strides) / broadcastedA.itemsize)

oriShape: (2, 6)
oriStrides: [6. 1.]
broadcastedShape: (1, 2, 2, 6)
broadcastedStrides: [0. 0. 6. 1.]


In [45]:
a = np.arange(12).reshape(1, 1, 2, 6)
print("oriShape:", a.shape)
print("oriStrides:", np.array(a.strides) / a.itemsize)
broadcastedA = np.broadcast_to(a, (1, 2, 2, 6))
print("broadcastedShape:", broadcastedA.shape)
print("broadcastedStrides:", np.array(broadcastedA.strides) / broadcastedA.itemsize)

oriShape: (1, 1, 2, 6)
oriStrides: [12. 12.  6.  1.]
broadcastedShape: (1, 2, 2, 6)
broadcastedStrides: [0. 0. 6. 1.]


In [8]:
a = np.arange(9).reshape(3, 3)
b = np.array([10, 20, 30])
print(a.shape)
print(b.shape)
a + b

(3, 3)
(3,)


array([[10, 21, 32],
       [13, 24, 35],
       [16, 27, 38]])

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.strides)
sum(np.array([0, 1]) * a.strides)

(12, 4)


4

In [8]:
a[0, 1]

2

In [9]:
y = np.reshape(np.arange(2*3*4), (2,3,4))
print(y)

print(y.strides)
print(y[1,1,1])

offset=sum(y.strides * np.array((1,1,1)))
offset/y.itemsize

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(48, 16, 4)
17


17.0

In [11]:
sum(y.strides * np.array((1,1,1)))
# offset/y.itemsize

68

In [2]:
a = np.arange(9).reshape((3, 3))
print(f"{a.itemsize=}")
print(a)
print(f"{a.shape=}")
print(f"{a.strides=}")

a.itemsize=4
[[0 1 2]
 [3 4 5]
 [6 7 8]]
a.shape=(3, 3)
a.strides=(12, 4)


In [3]:
b = np.arange(3)
print(f"{b.itemsize=}")
print(b)
print(f"{b.shape=}")
print(f"{b.strides=}")

b.itemsize=4
[0 1 2]
b.shape=(3,)
b.strides=(4,)


In [10]:
np.broadcast_to(b, (3, 3)).strides

(0, 4)

In [5]:
a + b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [97]:
a = np.arange(3).reshape((3, 1))
print(f"{a.itemsize=}")
print(a)
print(f"{a.shape=}")
print(f"{a.strides=}")

a = np.broadcast_to(a, (3, 2))
print(a)
print(f"{a.shape=}")
print(f"{a.strides=}")

a.itemsize=4
[[0]
 [1]
 [2]]
a.shape=(3, 1)
a.strides=(4, 4)
[[0 0]
 [1 1]
 [2 2]]
a.shape=(3, 2)
a.strides=(4, 0)


In [101]:
A = np.arange(24).reshape(3,2,4)
B = np.arange(3)[:, None, None]
print(f"{A=}\n{A.shape=}")
print(f"{B=}\n{B.shape=}")

A=array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])
A.shape=(3, 2, 4)
B=array([[[0]],

       [[1]],

       [[2]]])
B.shape=(3, 1, 1)


In [103]:
it = np.nditer((A, B), flags=['external_loop'])
while not it.finished:
    print(it[:])
    it.iternext()

(array([0, 1, 2, 3, 4, 5, 6, 7]), array([0, 0, 0, 0, 0, 0, 0, 0]))
(array([ 8,  9, 10, 11, 12, 13, 14, 15]), array([1, 1, 1, 1, 1, 1, 1, 1]))
(array([16, 17, 18, 19, 20, 21, 22, 23]), array([2, 2, 2, 2, 2, 2, 2, 2]))


In [104]:
print(A + B)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[18 19 20 21]
  [22 23 24 25]]]


In [112]:
C = np.arange(2)[None,:,None]
print(C)
it = np.nditer((A,C), flags=['external_loop'])
while not it.finished:
    print(it[:])
    it.iternext()

[[[0]
  [1]]]
(array([0, 1, 2, 3]), array([0, 0, 0, 0]))
(array([4, 5, 6, 7]), array([1, 1, 1, 1]))
(array([ 8,  9, 10, 11]), array([0, 0, 0, 0]))
(array([12, 13, 14, 15]), array([1, 1, 1, 1]))
(array([16, 17, 18, 19]), array([0, 0, 0, 0]))
(array([20, 21, 22, 23]), array([1, 1, 1, 1]))


In [113]:
print(A + C)

[[[ 0  1  2  3]
  [ 5  6  7  8]]

 [[ 8  9 10 11]
  [13 14 15 16]]

 [[16 17 18 19]
  [21 22 23 24]]]


In [116]:
np.nditer((A, C))

[(array(0), array(0)),
 (array(1), array(0)),
 (array(2), array(0)),
 (array(3), array(0)),
 (array(4), array(1)),
 (array(5), array(1)),
 (array(6), array(1)),
 (array(7), array(1)),
 (array(8), array(0)),
 (array(9), array(0)),
 (array(10), array(0)),
 (array(11), array(0)),
 (array(12), array(1)),
 (array(13), array(1)),
 (array(14), array(1)),
 (array(15), array(1)),
 (array(16), array(0)),
 (array(17), array(0)),
 (array(18), array(0)),
 (array(19), array(0)),
 (array(20), array(1)),
 (array(21), array(1)),
 (array(22), array(1)),
 (array(23), array(1))]

In [118]:
np.broadcast_arrays(A, B)

[array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],
 
        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],
 
        [[16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[[0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[2, 2, 2, 2],
         [2, 2, 2, 2]]])]

In [119]:
x = np.array([1, 2, 3])
print(f"{x.strides=}")
broadcasted_x = np.broadcast_to(x, (3, 3))
print(f"{broadcasted_x.strides=}")

x.strides=(4,)
broadcasted_x.strides=(0, 4)


In [122]:
x.__array_interface__

{'data': (2076584971792, False),
 'strides': None,
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (3,),
 'version': 3}

In [121]:
broadcasted_x.__array_interface__

{'data': (2076584971792, True),
 'strides': (0, 4),
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (3, 3),
 'version': 3}

In [124]:
test_x = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
test_x.__array_interface__

{'data': (2076061247312, False),
 'strides': None,
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (3, 3),
 'version': 3}

In [126]:
broadcasted_x.size

9